### ISSUE TITLE
No output for build number

### ISSUE THREAD

**Issue by Mark-McCracken** [guardian/actions-riff-raff#52]
We can't currently get the build number usefully.
End users can possibly work out the build number,
but it would be convenient if we could use something like [this](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), so that we can show the build number, with a link to riff-raff or the s3 bucket.

(Just need to bear in mind the edge case where users might have multiple riff-raff uploads in a single action)

**Comment by akash1810** [comment]
I think this is done in https://github.com/guardian/actions-riff-raff/pull/20?
